In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("data.csv")

In [3]:
df

           fever  bodyPain  age  runnyNose  diffbreath  infectionProb
0      98.455335         1   10          0           0              1
1     102.425956         1   83          0           0              0
2     100.752712         1   92          1           0              0
3     101.708475         0   41          1           1              0
4      98.827673         1   33          1           1              1
5     101.435114         0   66          1           0              0
6      98.514040         1   30          0           0              1
7     102.859176         0   45          0           0              1
8      98.568122         1   43          1          -1              0
9     101.929031         0   36          0           1              0
10     99.889124         1   86          0           0              0
11    101.371842         0   92          1           0              0
12    101.316246         1   20          0           1              0
13    103.549397         1   47          1          -1              0
14    101.564468         1   74          1           1              1
15    102.126751         0   71          1           1              1
16    100.383290         0   47          1          -1              0
17     98.429616         0   63          0          -1              1
18    100.621568         1   53          0          -1              0
19    100.791864         0   50          1          -1              0
20    100.265210         1   10          0           0              1
21    101.527046         0   45          1           1              1
22     99.299596         0   53          1          -1              0
23    103.335710         0   49          0           0              0
24     99.486476         0   52          0           0              0
25     98.565170         0   23          1          -1              1
26    102.353897         1  100          0           0              0
27     98.583636         1   93          1           0              1
28    100.548134         0   18          1           0              1
29    100.934557         0   42          0           0              0
...          ...       ...  ...        ...         ...            ...
9969   99.315935         0   96          0           0              0
9970   99.227403         0   73          1           1              0
9971   99.671806         0   31          1           1              0
9972  101.119132         1   30          1          -1              0
9973   98.056785         1   69          0           0              0
9974  101.345579         0   66          0          -1              0
9975  102.555306         1   71          0           0              0
9976   99.009739         1   59          0           1              1
9977  100.913427         0   15          0          -1              0
9978  102.720188         0   22          0          -1              1
9979  101.340735         0   96          1          -1              1
9980  101.136837         0   82          1           0              1
9981  103.418983         1   50          1          -1              1
9982  103.275116         1   90          0           1              1
9983  100.631699         1   82          0           0              1
9984   99.589529         0   31          0          -1              0
9985  102.866101         1   10          1          -1              1
9986  102.125355         0   37          0           0              0
9987  102.014353         0   36          0          -1              0
9988  101.500691         0    6          1           1              1
9989  100.682240         1   45          0           1              0
9990  102.867970         0   71          1          -1              1
9991  100.974676         1   36          1           0              1
9992   98.300477         0   13          1           0              1
9993  100.444186         1   50          1          -1              1
9994   98.352360         0   44          1           0              1
9995  100.721010         1   90          0           1              0
9996  102.766492         1   89          0           1              0
9997  102.942802         0   74          1           0              1
9998   99.585365         1   74          0           0              1

[9999 rows x 6 columns]

In [4]:
df.describe()

,fever,bodyPain,age,runnyNose,diffbreath,infectionProb
count,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000
mean,100.987447,0.504050,50.643064,0.493549,0.000900,0.499950
std,1.712371,0.500009,28.736591,0.499983,0.814022,0.500025
min,98.000288,0.000000,1.000000,0.000000,-1.000000,0.000000
25%,99.498738,0.000000,26.000000,0.000000,-1.000000,0.000000
50%,101.012088,1.000000,51.000000,0.000000,0.000000,0.000000
75%,102.472299,1.000000,76.000000,1.000000,1.000000,1.000000
max,103.999090,1.000000,100.000000,1.000000,1.000000,1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 6 columns):
fever            9999 non-null float64
bodyPain         9999 non-null int64
age              9999 non-null int64
runnyNose        9999 non-null int64
diffbreath       9999 non-null int64
infectionProb    9999 non-null int64
dtypes: float64(1), int64(5)
memory usage: 468.8 KB

In [6]:
df['diffbreath'].value_counts()

 0    3374
 1    3317
-1    3308
Name: diffbreath, dtype: int64

In [7]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled=np.random.permutation(len(data))
    test_set_size=int(len(data)*ratio)
    test_indices=shuffled[:test_set_size]
    train_indices=shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]

train,test= data_split(df,0.2)

In [8]:
train

           fever  bodyPain  age  runnyNose  diffbreath  infectionProb
8871  102.877607         1   92          0           1              0
9253  101.297000         0   15          1          -1              1
1561  100.218177         1   34          0           0              0
1670   99.719041         0   52          1           0              1
6086  101.004494         1   77          1           1              1
7332   98.935107         1   59          0           1              1
7461  100.868667         0   74          0           0              1
8828  102.425361         1   46          1          -1              0
7944  103.234584         1   65          0          -1              0
3508  103.570988         0   71          1          -1              1
2002  100.064444         0   48          1          -1              1
5865  101.969829         1   89          1          -1              1
168   100.875762         1   53          1          -1              1
2588  100.291556         0   83          1          -1              0
6400   98.896890         0   22          0           0              0
9528   98.808888         1   35          0          -1              1
8835  103.283100         1   43          1           0              1
6510  101.099972         0   99          1           1              0
4907   98.596778         1   68          0          -1              1
6394  103.707556         0    1          0          -1              0
8559   98.043314         1    2          0           1              1
4891  101.209468         1   11          0          -1              0
9937   99.119207         0    8          1           1              0
6520  103.026130         1   23          0           1              0
5181   99.733206         1   36          1          -1              1
6646  102.168577         1   18          0           1              1
7381  102.570013         0   61          1          -1              0
210    99.778908         1   73          0           1              1
6950  103.695698         0   53          1           0              0
1919  100.429049         1   17          0           0              0
...          ...       ...  ...        ...         ...            ...
2734  100.531078         0   47          1           1              0
189   103.484657         1   55          0           0              0
9167   99.852373         0   76          0           0              0
2747  101.798908         1   40          1           1              0
2047   99.281423         1   94          1           0              0
7849   99.200160         1   37          1           1              1
2558   99.805039         0   57          0          -1              1
9274  103.220464         1   34          1           1              1
8666  101.100675         1   32          0           0              1
6396  102.475044         0   37          0          -1              1
3385  102.064205         0   34          0           0              0
4555   99.984881         0   68          1          -1              1
1184  103.598644         0   78          1           1              0
6420  103.737405         0   99          1           1              1
5051  103.285352         1   32          1           1              1
5311   98.243460         0   76          0           1              0
2433  101.078621         1   82          0          -1              1
6949  100.584491         1   87          0           0              0
769    99.184942         1   21          0          -1              0
1685  103.032422         1    3          1           0              0
8322   98.087830         1   32          0           0              1
5578  101.942638         0   12          1           1              0
4426  102.539690         1   18          1           1              1
466   102.876800         1    9          1          -1              0
6265   98.776079         1   70          1          -1              1
5734  101.516635         0  100          1           0              0
5191   98.968737         0   51          0           0              0
5390  102.598152         0   49          1           1              1
860   100.287993         1    2          0           0              1
7270   99.003600         0   67          1           0              0

[8000 rows x 6 columns]

In [9]:
test

           fever  bodyPain  age  runnyNose  diffbreath  infectionProb
5344   99.622645         1   59          1          -1              1
7444   98.699378         0   21          1           0              1
1731  101.817660         0    3          0           0              0
8719  102.125438         0   11          0          -1              1
4521  102.890043         1   10          1           1              1
7453   98.029316         0    3          1           0              0
576   102.664674         0   92          1          -1              1
7428  102.068266         1   71          0          -1              0
5577  102.589297         0   67          0          -1              0
439   100.632457         0   29          0           1              0
2750  100.444871         0   85          1           0              1
5730  101.370998         0    2          0           1              0
5271   99.551916         0   84          1           1              1
5652  100.892987         0    4          0          -1              1
3999  101.421642         1   41          0           0              1
4556   99.190766         1   50          0          -1              0
582   100.750824         1   32          0          -1              1
6289  103.301114         1   84          1           0              0
7050   98.687833         0   85          1          -1              0
4894  103.020505         1   38          0          -1              1
8697   98.762398         1   83          1          -1              0
2249   98.894830         0   42          1           1              0
4639  100.123684         0   83          1          -1              1
7191  101.900887         1   48          0          -1              1
5872  102.875578         0   58          1           1              0
6330  100.169404         0    5          1           1              1
1963   98.572806         1    5          0          -1              0
8242  102.140628         1   94          0           0              0
6589   98.080264         0   93          0           0              0
8846   99.468950         1   95          1           1              1
...          ...       ...  ...        ...         ...            ...
3621  103.577919         0   76          0           1              1
4847  100.170352         0   94          1          -1              1
2291  101.656080         0   95          0           1              1
2133  103.290650         1   26          1           1              1
550    99.684883         1   82          1           0              0
1740  100.918787         1   55          1          -1              0
5288  102.272253         1   71          1           0              1
1817  103.823388         0   76          0           1              0
9215  101.154603         0   72          0          -1              0
5180   98.469152         1   90          0          -1              1
3018  103.909006         0   79          1          -1              0
17     98.429616         0   63          0          -1              1
1770   98.959024         1   87          0          -1              0
1888  101.100456         1   68          0           0              0
2152   98.962770         0    3          1           0              1
1642  100.085913         0   79          0           1              1
7915  102.375599         0   95          0          -1              0
4193   99.593071         1   89          0           0              1
4747  100.604768         1   19          0           0              1
4830  100.945801         1   20          0           1              1
533   102.279409         1   57          0           0              1
132   102.049322         0   97          1           1              1
4864  102.892248         0   52          1           0              1
8457  103.623648         1   27          0           0              0
964   102.512665         1   74          0           0              1
9210  101.811520         1   22          0           1              1
9448   98.715271         0   97          0          -1              1
8284  100.785388         1   63          1          -1              1
7852   98.106877         1   62          1           1              0
1095  102.117611         0   97          1           1              0

[1999 rows x 6 columns]

In [10]:
X_train=train[['fever','bodyPain','age','runnyNose','diffbreath']].to_numpy()
X_test=test[['fever','bodyPain','age','runnyNose','diffbreath']].to_numpy()

In [11]:
Y_train=train[['infectionProb']].to_numpy().reshape(8000,)
Y_test=test[['infectionProb']].to_numpy().reshape(1999,)

In [12]:
X_train

array([[102.8776074 ,   1.        ,  92.        ,   0.        ,
          1.        ],
       [101.2970003 ,   0.        ,  15.        ,   1.        ,
         -1.        ],
       [100.2181768 ,   1.        ,  34.        ,   0.        ,
          0.        ],
       ...,
       [102.5981515 ,   0.        ,  49.        ,   1.        ,
          1.        ],
       [100.2879928 ,   1.        ,   2.        ,   0.        ,
          0.        ],
       [ 99.00359973,   0.        ,  67.        ,   1.        ,
          0.        ]])

In [13]:
X_test

array([[ 99.62264531,   1.        ,  59.        ,   1.        ,
         -1.        ],
       [ 98.6993782 ,   0.        ,  21.        ,   1.        ,
          0.        ],
       [101.8176603 ,   0.        ,   3.        ,   0.        ,
          0.        ],
       ...,
       [100.7853877 ,   1.        ,  63.        ,   1.        ,
         -1.        ],
       [ 98.10687683,   1.        ,  62.        ,   1.        ,
          1.        ],
       [102.1176115 ,   0.        ,  97.        ,   1.        ,
          1.        ]])

In [14]:
Y_train

array([0, 1, 0, ..., 1, 1, 0])

In [15]:
Y_test

array([1, 1, 0, ..., 1, 0, 0])

In [16]:
logreg=LogisticRegression()

In [17]:
logreg.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [20]:
input_features=[104,1,22,1,0]
infProb = logreg.predict_proba([input_features])[0][1]

In [21]:
infProb

0.5182730144520166